### ISSUE TITLE
How would I add alert?

### ISSUE THREAD

**Issue by likern** [cossssmin/gridsome-starter-bleda#12]
Hello! Thank you for such a great starter.

I have a small problem - I've seen that `<alert>` component. How I might use it inside blog post **directly**? I would want to add alerts to some posts like `Note: this tutorial was tested on Ubuntu 18.04 LTS`. Is it possible?

**Comment by cossssmin** [comment]
Hey, you're welcome 😊

So right now you can't use Vue components inside Markdown files, which is what this starter uses for content. They're [working on it](https://github.com/gridsome/gridsome/pull/424) though, so you'll be able to do that soon, probably in `v0.7.0` or even earlier.

Another idea would be to have some string in your post's Front Matter, and then call the `<alert>` component somewhere right in the `Post.vue` template, passing it the Front Matter variable.

**Comment by likern** [comment]
Thank you, I will try your approach ;) And also small relevant question: do you have plans to add more statuses and color to alert. For example, info, success, error, etc. =)

**Comment by cossssmin** [comment]
You can use any of the bg/color classes from Tailwind, and you can of course define new ones in your `tailwind.config.js`. I'm not planning on creating classes such as `info` or `success`, but you could easily do that by [extracting Tailwind utilities](https://tailwindcss.com/docs/extracting-components).
