### ISSUE TITLE
Question: how to add postcss-preset-env?

### ISSUE THREAD

**Issue by sergeyfilimonov** [cossssmin/gridsome-starter-bleda#22]
Thank you for this great starter! But how to add `postcss-preset-env` plugin in this config? Just adding `require('postcss-preset-env')` doesn't work

**Comment by cossssmin** [comment]
Never tried it, you say adding it like in the [docs](https://tailwindcss.com/docs/using-with-preprocessors/#future-css-features), after Tailwind itself, doesn't work?

i.e. like this?

```js
options.plugins.unshift(...[
  require('postcss-import'),
  require('postcss-nested'),
  require('tailwindcss'),
  require('postcss-preset-env')({ stage: 1 }),
])
```

**Comment by sergeyfilimonov** [comment]
@cossssmin thanks! I missed `({ stage: 1 })` part, it didn't work without out
