### ISSUE TITLE
Gridsome serve results with 404

### ISSUE THREAD

**Issue by gustojs** [cossssmin/gridsome-starter-bleda#23]
Hi, thanks for a great plugin.

Out of the box, after creating new project, `gridsome serve` shows the following content:

```
{"code":404,"message":"Could not find /"}
```

WLS 1, node 10.8

Any potential reason you can think of?

**Comment by cossssmin** [comment]
Not seeing that listed in the Gridsome CLI [docs](https://gridsome.org/docs/gridsome-cli), maybe it's a deprecated command? I see it does work if you spin up the default project with `gridsome create my-gridsome-site`, so I really don't know what to say. I personally never used it, only used `gridsome develop`, which works fine 🤷‍♂️

**Comment by gustojs** [comment]
Thanks for the answer. :) Here's the answer I got from @hjvedvik:
```
The gridsome serve command is not deprecated :slight_smile: Just haven't documented it yet because it is very unstable and not meant to be used yet.
```
With this, we can close the issue until the command becomes stable and documented.
