### ISSUE TITLE
forestry conf files

### ISSUE THREAD

**Issue by lorvent** [cossssmin/gridsome-starter-bleda#30]
pls consider adding forestry config files...thats helps writing blog posts easily

**Comment by cossssmin** [comment]
Someone could write a tutorial on that or fork it and create a Forestry starter. Bleda will remain a Markdown blog starter.

**Comment by lorvent** [comment]
i get your point but forestry is still markdown but instead of writing from your pc, you can write posts from a website.

**Comment by lorvent** [comment]
and to make it forestry compatible, we just need to add a .forestry folder and conf file inside.

**Comment by cossssmin** [comment]
I understand, but there could be lots and lots of services like Forestry - what do we do then? Add config files for each of them, pick a favorite? I prefer keeping such third parties in userland, especially since it sounds so easy to just add a config file.
