### ISSUE TITLE
Error on gridsome develop - @apply cannot be used with '-mx-6'

### ISSUE THREAD

**Issue by dixonge** [cossssmin/gridsome-starter-bleda#4]
``` ERROR  Failed to compile with 1 errors                               8:21:28 AM

 error  in ./src/assets/css/main.css?vue&type=style&index=0&lang=css&

Syntax Error: SyntaxError

(46:5) `@apply` cannot be used with `.-mx-6` because `.-mx-6` either cannot be found, or its actual definition includes a pseudo-selector like :hover, :active, etc. If you're sure that `.-mx-6` exists, make sure that any `@import` statements are being properly processed *before* Tailwind CSS sees your CSS, as `@apply` can only be used for classes in the same CSS tree.

  44 |   pre.shiki {
  45 |     @apply bg-gray-codeblock !important;
> 46 |     @apply border border-gray-300 -mx-6 p-6 mb-4 text-sm font-mono leading-code overflow-x-auto scrolling-touch;
     |     ^
  47 |   }
```

**Comment by dixonge** [comment]
to verify - removed '-mx-y' from markdown.css - gridsome develop successfully compiled and launched site. Not familiar enough with tailwind to know what styling is changed by that, just wanted you to know.

**Comment by cossssmin** [comment]
Are you perhaps using Tailwind CSS `v1.0.0-beta.6` or newer? If so, that might be causing it (see [release notes](https://github.com/tailwindcss/tailwindcss/releases/tag/v1.0.0-beta.6), there's an upgrade guide there as well). The class is used for negative `margin`, which has been changed in that release.

I'll try to update the Tailwind config and `package.json` to use the latest Tailwind beta these days.

**Comment by dixonge** [comment]
I was using whatever came with the gridsome install. This was my first time using Tailwind

**Comment by cossssmin** [comment]
Yeah, most likely it installed a newer Tailwind beta, where the negative margins have changed. Looks like Tailwind CSS v1.0.0 will launch these days, so I'll bump the version and fix the `markdown.css` once that is out.

**Comment by cossssmin** [comment]
Tailwind CSS 1.0.0 just launched, I just pushed a commit that fixes this.
