### ISSUE TITLE
gridsome build error but developer works with g-image in rendering

### ISSUE THREAD

**Issue by Mejanhaque** [cossssmin/gridsome-starter-bleda#56]
I updated the PostItem.vue image html tag with g-image by following the gridsome documentation. when i went to publish my site on netlify it failed to build. i thought it was tag or author page errors. but when i changed g-image tag to image tag it woked perfectly. is it a gridsome bug? by the way, thanks for creating this demo app. it really helped to learn more about gridsome.

**Comment by cossssmin** [comment]
Hey sorry for the late reply, missed your question. 

Though there isn't any HTML image tag in [PostItem.vue](https://github.com/cossssmin/gridsome-starter-bleda/blob/master/src/components/PostItem.vue), I just tested this and it works perfectly fine (both when developing and when running `gridsome build`, using Gridsome v0.7.12). So in case you haven't resolved it already, I suggest double checking your edits and eventually ask for help on the Gridsome discord. 

Also, you're welcome, happy to hear you found it useful 😊
