### ISSUE TITLE
Only default.png is being shown on Author template

### ISSUE THREAD

**Issue by mallim** [cossssmin/gridsome-starter-bleda#8]
Thanks for the great gridsome starter

I discovered a bug that although there are images for bleda.png and gridsome.png  in static\images\folder, only default.png is being displayed on Author.vue or the URL/author/gridsome or URL/author/bleda pages.

**Comment by cossssmin** [comment]
You’re welcome! 😊

Author archives pages are not coded to display the author avatar - if you’re referring to the little user icon at the top, that’s just an SVG icon that shows no matter the author.

**Comment by mallim** [comment]
Thanks for your clarification.

My understanding on the author avatar is wrong then. https://gridsome-starter-bleda.netlify.com/adding-a-post-author/

**Comment by cossssmin** [comment]
The author avatar will only show up at the bottom of each post. Maybe I should mention it there :)
